name: Docker Build & Publish

on:
  push:
    branch: [ 'main' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  push_to_registry:

    runs-on: ubuntu-20.04
    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set build variables
        run: |
          echo "BUILD_TAG=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          if [[ ${{ github.ref_name }} == *.stable* ]]; then
            echo "BUILD_TYPE=stable" >> "$GITHUB_ENV"
          else
            echo "BUILD_TYPE=latest" >> "$GITHUB_ENV"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ contains(github.ref, 'ref/tags/v') }}
          build-args: |
            version=${{ env.BUILD_TAG }}
            branch=${{ env.BUILD_TYPE }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_TYPE }}
